name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # You can adjust this to your preferred Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build and Deploy
      run: |
        git config --global user.name ${{ github.actor }}
        git config --global user.email ${{ github.actor }}@users.noreply.github.com
        npm run deploy
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}